# Generated by Django 5.2 on 2025-05-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_problem_delete_todoitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="wa1",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="problem",
            name="wa2",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="problem",
            name="wa3",
            field=models.IntegerField(default=3),
        ),
    ]
