# Generated by Django 5.2 on 2025-05-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_problem_wa1_problem_wa2_problem_wa3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="wa2",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="problem",
            name="wa3",
            field=models.IntegerField(default=1),
        ),
    ]
